fix enabling prometheus metrics plugin
tarantool/docker pull request #239
Opened 2022-07-06 09:26 UTC by foxzi

Fix error enabling prometheus metrics rocks. 

Fix issue #237

2022-07-06 09:27 UTC, NickVolynkin commented on files/tarantool-entrypoint.lua
> +--        require('metrics.default_metrics.tarantool').enable()
remove the old line

2022-07-06 10:13 UTC, artembo requested changes
using git we don't comment the old code, because it stays in the repo anyway
please, remove the comment

2022-07-14 14:57 UTC, foxzi commented on files/tarantool-entrypoint.lua
> +--        require('metrics.default_metrics.tarantool').enable()
done

2022-07-14 14:58 UTC, artembo approved these changes

2022-07-14 15:13 UTC, olegrok approved these changes

2022-07-18 08:18 UTC, NickVolynkin approved these changes

2022-07-18 08:19 UTC, merged